### ISSUE TITLE
Visbility request for FormFieldState instead of FormField

### ISSUE THREAD

**Issue by Yvee1** [jtdaugherty/brick#496]
Hi. When using a Form inside a viewport, a visibility request is made only for the `FormField` that is in focus. However, I think in most cases it is more useful make a visibility request for the entire `FormFieldState` widget instead. It would be nice to have a feature to enable this, or to have this functionality by default.

An example follows.
In the below image the field with input `4` is made visible but the label on the left consists of multiple lines of which only the first is visible.
![image](https://github.com/jtdaugherty/brick/assets/30909373/62913452-479f-4157-928b-b2fc86d88977)

The desired functionality makes the entire `FormFieldState` visible, including the label, giving the below result.
![image](https://github.com/jtdaugherty/brick/assets/30909373/c1ac639c-f7ae-4cbe-9e13-beca0dda7cda)

**Comment by jtdaugherty** [comment]
The API enhancement for this is now released in 2.2.

**Comment by Yvee1** [comment]
Thanks!

**Comment by Yvee1** [comment]
I just tried out the new version, but `ShowAugmentedField` does not do exactly what I want. 
ShowAugmentedField, as described in the documentation:
> Make all inputs in the focused field visible. For composite fields this will bring all options into view as long as the viewport is large enough to show them all.

Personally, I would call this `ShowCompositeField`.
My version of `ShowAugmentedField` would be:
> Make visible all inputs and render helpers in the focused field.

An example use case is what I sent before: I would like the label of the field, added using the `@@=` combinator, to be made visible.

**Comment by jtdaugherty** [comment]
Thanks for letting me know that the original approach didn’t work. I’ve released an updated API in 2.3.

**Comment by Yvee1** [comment]
You are very quick! Thanks

**Comment by Yvee1** [comment]
Okay sorry, just checked the new version. You forgot to check whether the field is in focus:
```
maybeHelperVisible = if visMode == ShowAugmentedField then visible else id
```
should be
  ```
maybeHelperVisible = if foc && visMode == ShowAugmentedField then visible else id
```

**Comment by jtdaugherty** [comment]
Sorry, that’s now fixed in 2.3.1.
